services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./conf/core-site.xml:/etc/trino/etc/hadoop/core-site.xml
      - ./conf/metastore-site.xml:/etc/trino/metastore-site.xml
      - ./etc/catalog:/etc/trino/catalog
    networks:
      - trino-network

  postgres:
    image: 'postgres:11'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    networks:
      - trino-network

  postgres_src:
    image: 'postgres:11'
    hostname: postgres_src
    expose:
      - '5433'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    networks:
      - trino-network

  hive-metastore:
    image: my-hive-metastore
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      - ./conf/core-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/core-site.xml:ro
      - ./conf/hadoop-aws-3.2.0.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/hadoop-aws-3.2.0.jar
      - ./conf/aws-java-sdk-bundle-1.11.375.jar:/opt/apache-hive-metastore-3.0.0-bin/lib/aws-java-sdk-bundle-1.11.375.jar
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: dockerminio
      MINIO_SECRET_KEY: dock_master123
      MINIO_ROOT_USER: dockerminio
      MINIO_ROOT_PASSWORD: dock_master123
    command: server /data --console-address ":9001" 
    networks:
      - trino-network

volumes:
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge
